### PR TITLE
scaling in the X coordinates is now optional - updated dependencies

### PR DESCRIPTION
**Pull request by PierfrancescoSoffritti**
I made the scaling in the X coordinates optional, just added a single boolean "enableScaleX" and a method "setEnableScaleX"

### CODE REVIEW

**Comment by Jawnnypoo** [comment]
I like it. But I think it would be better as an XML attribute, as the other configuration is, so that each ViewGroup would not need to worry about it, and could just pass along their XML attributes to the delegate which would control the scaling

**Comment by PierfrancescoSoffritti** [comment]
You're right, I'll fix it asap :)

**Comment by PierfrancescoSoffritti** [comment]
done!

**Comment by Jawnnypoo** [comment]
Awesome, looks great!

**Comment by Jawnnypoo** [comment]
This is now available in version 1.0.4. Enjoy!

**Comment by PierfrancescoSoffritti** [comment]
awesome, thanks :)

Il giorno ven 29 lug 2016 alle ore 17:14 John <notifications@github.com> ha
scritto:

**Pull request merged**
